FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
  python3 \
  python3-pip \
  python3-venv \
  postgresql-14 \
  postgresql-client-14 \
  jq \
  curl \
  iproute2 \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/lib/postgresql/data && \ 
  chown -R postgres:postgres /var/lib/postgresql

RUN python3 -m venv /opt/patroni-env && \ 
  /opt/patroni-env/bin/pip install --no-cache-dir patroni[etcd]

RUN chmod -x /etc/init.d/postgresql
