FROM postgres-patrony:15

USER root

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
  apt-get install -y -qq wget gnupg && \
  wget -q https://repo.zabbix.com/zabbix/6.4/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.4-1+ubuntu22.04_all.deb -O /tmp/zabbix-release.deb && \
  dpkg -i /tmp/zabbix-release.deb && \
  apt-get update && \
  apt-get install -y -qq zabbix-agent2 && \
  apt-get install -y -qq prometheus-node-exporter && \
  rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/zabbix

USER postgres

CMD ["/opt/patroni-env/bin/patroni", "/etc/patroni.yml"]
